interval: 360
webhook: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX
channel: "#notifications-channel"
feeds:
  - https://www.cloudflarestatus.com/history.atom:
      exclude:
        - Customers
