name: publish
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '14'
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm i
    - name: Run linter
      run: npm run lint
    - name: Add NPM token
      if: github.ref == 'refs/heads/main'
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish
      if: github.ref == 'refs/heads/main'
      run: npx @lets/publish
    - name: Set Docker credentials
      if: github.ref == 'refs/heads/main'
      run: echo $DOCKER_PASSWORD | docker login --username omrilotan --password-stdin
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      if: github.ref == 'refs/heads/main'
      run: docker build --tag omrilotan/rss-notifier:latest .
    - name: Build
      if: github.ref == 'refs/heads/main'
      run: docker push omrilotan/rss-notifier:latest
